### ISSUE TITLE
gives error when making

### ISSUE THREAD

**Issue by alperenozyuksel** [srmainwaring/python-ignition#23]
/usr/bin/ld: /usr/local/lib/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against symbol `_ZN6google8protobuf8internal9ArenaImpl13thread_cache_E' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libprotobuf.a(common.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/gz_msgs_extras_lib.dir/build.make:108: libgz_msgs_extras_lib.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:4166: CMakeFiles/gz_msgs_extras_lib.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

I get this error when I make after successfully cmake...

**Comment by srmainwaring** [comment]
Insufficient details to be able to reproduce.
